using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ContactManager.Models
{
    public class Address // add a new table related to contact class
    {
        // primary key - generated by database
        public int AddressId { get; set; }
        [Required(ErrorMessage = "Please enter a street.")]
        public string Street { get; set; }
        public string LineTwo { get; set; }
        [Required(ErrorMessage = "Please enter a city.")]
        public string City { get; set; }
        [Required(ErrorMessage = "Please enter a state.")]
        public string State { get; set; }
        [Required(ErrorMessage = "Please enter a zip code.")]
        public int ZipCode { get; set; }
    }
}
